INSERT INTO APRSL (APRSE, APRSL_NUM, PRJCT_NUM, APRSL_KND, APRSL_ITEM, GRAD, APRSL_CN)VALUES ('e0022','10','0001','고객평가','업무수행평가','7','Very Nice!');
INSERT INTO APRSL (APRSE, APRSL_NUM, PRJCT_NUM, APRSL_KND, APRSL_ITEM, GRAD, APRSL_CN)VALUES ('e0022','10','0001','고객평가','커뮤니케이션평가','7','Very Nice!');
INSERT INTO APRSL (APRSE, APRSL_NUM, PRJCT_NUM, APRSL_KND, APRSL_ITEM, GRAD, APRSL_CN)VALUES ('e0022','e0023','0001','동료평가','업무수행평가','7','Very Nice!');
INSERT INTO APRSL (APRSE, APRSL_NUM, PRJCT_NUM, APRSL_KND, APRSL_ITEM, GRAD, APRSL_CN)VALUES ('e0022','e0023','0001','동료평가','커뮤니케이션평가','7','Very Nice!');
INSERT INTO APRSL (APRSE, APRSL_NUM, PRJCT_NUM, APRSL_KND, APRSL_ITEM, GRAD, APRSL_CN)VALUES ('e0022','e0021','0001','PM평가','업무수행평가','7','Very Nice!');
INSERT INTO APRSL (APRSE, APRSL_NUM, PRJCT_NUM, APRSL_KND, APRSL_ITEM, GRAD, APRSL_CN)VALUES ('e0022','e0021','0001','PM평가','커뮤니케이션평가','7','Very Nice!');
